export const LOAN_ABI = [
  {
    type: 'constructor',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: '_admin', internalType: 'address' },
      { type: 'address', name: '_lendingPool', internalType: 'address' },
      { type: 'address', name: '_liquidatePool', internalType: 'address' },
      { type: 'address', name: '_permittedNFT', internalType: 'address' },
      { type: 'address[]', name: '_permittedErc20s', internalType: 'address[]' },
    ],
  },
  {
    type: 'event',
    name: 'AdminFeeUpdated',
    inputs: [{ type: 'uint16', name: 'newAdminFee', internalType: 'uint16', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ERC20Permit',
    inputs: [
      { type: 'address', name: 'erc20Contract', internalType: 'address', indexed: true },
      { type: 'bool', name: 'isPermitted', internalType: 'bool', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LoanLiquidated',
    inputs: [
      { type: 'bytes32', name: 'loanId', internalType: 'bytes32', indexed: true },
      { type: 'address', name: 'borrower', internalType: 'address', indexed: true },
      { type: 'address', name: 'lender', internalType: 'address', indexed: true },
      { type: 'uint256', name: 'principalAmount', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'nftCollateralId', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'loanMaturityDate', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'loanLiquidationDate', internalType: 'uint256', indexed: false },
      { type: 'address', name: 'nftCollateralContract', internalType: 'address', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LoanRenegotiated',
    inputs: [
      { type: 'bytes32', name: 'loanId', internalType: 'bytes32', indexed: true },
      { type: 'address', name: 'borrower', internalType: 'address', indexed: true },
      { type: 'address', name: 'lender', internalType: 'address', indexed: true },
      { type: 'uint32', name: 'newLoanDuration', internalType: 'uint32', indexed: false },
      { type: 'uint256', name: 'renegotiationFee', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'renegotiationAdminFee', internalType: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LoanRepaid',
    inputs: [
      { type: 'bytes32', name: 'loanId', internalType: 'bytes32', indexed: true },
      { type: 'address', name: 'borrower', internalType: 'address', indexed: true },
      { type: 'address', name: 'lender', internalType: 'address', indexed: true },
      { type: 'address', name: 'treasury', internalType: 'address', indexed: false },
      { type: 'uint256', name: 'principalAmount', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'nftCollateralId', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'amountPaidToLender', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'adminFee', internalType: 'uint256', indexed: false },
      { type: 'uint256', name: 'amountToTreasury', internalType: 'uint256', indexed: false },
      { type: 'address', name: 'nftCollateralContract', internalType: 'address', indexed: false },
      { type: 'address', name: 'erc20Denomination', internalType: 'address', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LoanStarted',
    inputs: [
      { type: 'bytes32', name: 'loanId', internalType: 'bytes32', indexed: true },
      { type: 'address', name: 'borrower', internalType: 'address', indexed: true },
      { type: 'address', name: 'lender', internalType: 'address', indexed: true },
      {
        type: 'tuple',
        name: 'loanTerms',
        internalType: 'struct LoanData.LoanTerms',
        indexed: false,
        components: [
          { type: 'uint256', name: 'principalAmount', internalType: 'uint256' },
          { type: 'uint256', name: 'maximumRepaymentAmount', internalType: 'uint256' },
          { type: 'uint256', name: 'nftCollateralId', internalType: 'uint256' },
          { type: 'address', name: 'erc20Denomination', internalType: 'address' },
          { type: 'uint32', name: 'duration', internalType: 'uint32' },
          { type: 'uint16', name: 'adminFeeInBasisPoints', internalType: 'uint16' },
          { type: 'uint64', name: 'loanStartTime', internalType: 'uint64' },
          { type: 'address', name: 'nftCollateralContract', internalType: 'address' },
          { type: 'address', name: 'borrower', internalType: 'address' },
          { type: 'address', name: 'lender', internalType: 'address' },
          { type: 'uint8', name: 'status', internalType: 'enum LoanData.LoanStatus' },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MaximumLoanDurationUpdated',
    inputs: [{ type: 'uint256', name: 'newMaximumLoanDuration', internalType: 'uint256', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { type: 'address', name: 'previousOwner', internalType: 'address', indexed: true },
      { type: 'address', name: 'newOwner', internalType: 'address', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [{ type: 'address', name: 'account', internalType: 'address', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetLendingPool',
    inputs: [
      { type: 'address', name: 'oldValue', internalType: 'address', indexed: true },
      { type: 'address', name: 'newValue', internalType: 'address', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetLiquidatePool',
    inputs: [
      { type: 'address', name: 'oldValue', internalType: 'address', indexed: true },
      { type: 'address', name: 'newValue', internalType: 'address', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [{ type: 'address', name: 'account', internalType: 'address', indexed: false }],
    anonymous: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint16', name: '', internalType: 'uint16' }],
    name: 'HUNDRED_PERCENT',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'acceptOffer',
    inputs: [
      { type: 'bytes32', name: '_loanId', internalType: 'bytes32' },
      {
        type: 'tuple',
        name: '_offer',
        internalType: 'struct LoanData.Offer',
        components: [
          { type: 'uint256', name: 'principalAmount', internalType: 'uint256' },
          { type: 'uint256', name: 'maximumRepaymentAmount', internalType: 'uint256' },
          { type: 'uint256', name: 'nftCollateralId', internalType: 'uint256' },
          { type: 'address', name: 'nftCollateralContract', internalType: 'address' },
          { type: 'uint32', name: 'duration', internalType: 'uint32' },
          { type: 'uint16', name: 'adminFeeInBasisPoints', internalType: 'uint16' },
          { type: 'address', name: 'erc20Denomination', internalType: 'address' },
        ],
      },
      {
        type: 'tuple',
        name: '_signature',
        internalType: 'struct LoanData.Signature',
        components: [
          { type: 'uint256', name: 'nonce', internalType: 'uint256' },
          { type: 'uint256', name: 'expiry', internalType: 'uint256' },
          { type: 'address', name: 'signer', internalType: 'address' },
          { type: 'bytes', name: 'signature', internalType: 'bytes' },
        ],
      },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'acceptOfferLendingPool',
    inputs: [
      { type: 'bytes32', name: '_loanId', internalType: 'bytes32' },
      {
        type: 'tuple',
        name: '_offer',
        internalType: 'struct LoanData.Offer',
        components: [
          { type: 'uint256', name: 'principalAmount', internalType: 'uint256' },
          { type: 'uint256', name: 'maximumRepaymentAmount', internalType: 'uint256' },
          { type: 'uint256', name: 'nftCollateralId', internalType: 'uint256' },
          { type: 'address', name: 'nftCollateralContract', internalType: 'address' },
          { type: 'uint32', name: 'duration', internalType: 'uint32' },
          { type: 'uint16', name: 'adminFeeInBasisPoints', internalType: 'uint16' },
          { type: 'address', name: 'erc20Denomination', internalType: 'address' },
        ],
      },
      {
        type: 'tuple[]',
        name: '_signatures',
        internalType: 'struct LoanData.Signature[]',
        components: [
          { type: 'uint256', name: 'nonce', internalType: 'uint256' },
          { type: 'uint256', name: 'expiry', internalType: 'uint256' },
          { type: 'address', name: 'signer', internalType: 'address' },
          { type: 'bytes', name: 'signature', internalType: 'bytes' },
        ],
      },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint16', name: '', internalType: 'uint16' }],
    name: 'adminFeeInBasisPoints',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'cancelLoanCommitmentBeforeLoanHasBegun',
    inputs: [{ type: 'uint256', name: '_nonce', internalType: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'drainERC20Airdrop',
    inputs: [
      { type: 'address', name: '_tokenAddress', internalType: 'address' },
      { type: 'address', name: '_receiver', internalType: 'address' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'drainERC721Airdrop',
    inputs: [
      { type: 'address', name: '_tokenAddress', internalType: 'address' },
      { type: 'uint256', name: '_tokenId', internalType: 'uint256' },
      { type: 'address', name: '_receiver', internalType: 'address' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'getERC20Permit',
    inputs: [{ type: 'address', name: '_erc20', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'getPayoffAmount',
    inputs: [{ type: 'bytes32', name: '_loanId', internalType: 'bytes32' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'getWhetherNonceHasBeenUsedForUser',
    inputs: [
      { type: 'address', name: '_user', internalType: 'address' },
      { type: 'uint256', name: '_nonce', internalType: 'uint256' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'isValidLoanId',
    inputs: [{ type: 'bytes32', name: '_loanId', internalType: 'bytes32' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'lendingPool',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'liquidateOverdueLoan',
    inputs: [{ type: 'bytes32', name: '_loanId', internalType: 'bytes32' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'liquidatePool',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [
      { type: 'uint256', name: 'principalAmount', internalType: 'uint256' },
      { type: 'uint256', name: 'maximumRepaymentAmount', internalType: 'uint256' },
      { type: 'uint256', name: 'nftCollateralId', internalType: 'uint256' },
      { type: 'address', name: 'erc20Denomination', internalType: 'address' },
      { type: 'uint32', name: 'duration', internalType: 'uint32' },
      { type: 'uint16', name: 'adminFeeInBasisPoints', internalType: 'uint16' },
      { type: 'uint64', name: 'loanStartTime', internalType: 'uint64' },
      { type: 'address', name: 'nftCollateralContract', internalType: 'address' },
      { type: 'address', name: 'borrower', internalType: 'address' },
      { type: 'address', name: 'lender', internalType: 'address' },
      { type: 'uint8', name: 'status', internalType: 'enum LoanData.LoanStatus' },
    ],
    name: 'loanIdToLoan',
    inputs: [{ type: 'bytes32', name: '', internalType: 'bytes32' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'loanRepaidOrLiquidated',
    inputs: [{ type: 'bytes32', name: '', internalType: 'bytes32' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
    name: 'maximumLoanDuration',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'bytes4', name: '', internalType: 'bytes4' }],
    name: 'onERC721Received',
    inputs: [
      { type: 'address', name: '', internalType: 'address' },
      { type: 'address', name: '', internalType: 'address' },
      { type: 'uint256', name: '', internalType: 'uint256' },
      { type: 'bytes', name: '', internalType: 'bytes' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'address' }],
    name: 'owner',
    inputs: [],
  },
  { type: 'function', stateMutability: 'nonpayable', outputs: [], name: 'pause', inputs: [] },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
    name: 'paused',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'payBackLoan',
    inputs: [{ type: 'bytes32', name: '_loanId', internalType: 'bytes32' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', internalType: 'contract IPermittedNFTs' }],
    name: 'permittedNFTs',
    inputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'renegotiateLoan',
    inputs: [
      { type: 'bytes32', name: '_loanId', internalType: 'bytes32' },
      { type: 'uint32', name: '_newLoanDuration', internalType: 'uint32' },
      { type: 'uint256', name: '_renegotiationFee', internalType: 'uint256' },
      { type: 'uint256', name: '_lenderNonce', internalType: 'uint256' },
      { type: 'uint256', name: '_expiry', internalType: 'uint256' },
      { type: 'bytes', name: '_lenderSignature', internalType: 'bytes' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'setERC20Permit',
    inputs: [
      { type: 'address', name: '_erc20', internalType: 'address' },
      { type: 'bool', name: '_permit', internalType: 'bool' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'setERC20Permits',
    inputs: [
      { type: 'address[]', name: '_erc20s', internalType: 'address[]' },
      { type: 'bool[]', name: '_permits', internalType: 'bool[]' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'setLendingPool',
    inputs: [{ type: 'address', name: '_lendingPool', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'setLiquidatePool',
    inputs: [{ type: 'address', name: '_liquidatePool', internalType: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'transferOwnership',
    inputs: [{ type: 'address', name: '_newOwner', internalType: 'address' }],
  },
  { type: 'function', stateMutability: 'nonpayable', outputs: [], name: 'unpause', inputs: [] },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'updateAdminFee',
    inputs: [{ type: 'uint16', name: '_newAdminFeeInBasisPoints', internalType: 'uint16' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    outputs: [],
    name: 'updateMaximumLoanDuration',
    inputs: [{ type: 'uint256', name: '_newMaximumLoanDuration', internalType: 'uint256' }],
  },
];
